autoDetectedPackages:
- study.online.api.client
- study.online.api.config
- study.online.api.model
- study.online.base.advice
- study.online.base.config
- study.online.base.constant
- study.online.base.exception
- study.online.base.model
- study.online.content
- study.online.gateway
- study.online.media
- study.online.messagesdk.config
- study.online.messagesdk.mapper
- study.online.messagesdk.model
- study.online.messagesdk.service
- study.online.system
enableAutoDetect: true
entryDisplayConfig:
  excludedPathPatterns: []
  skipJsCss: true
funcDisplayConfig:
  skipConstructors: false
  skipFieldAccess: true
  skipFieldChange: true
  skipGetters: false
  skipNonProjectPackages: false
  skipPrivateMethods: false
  skipSetters: false
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: manual
sourceDisplayConfig:
  color: blue
startOnDebug: false
