server:
    port: 8082
    servlet:
        context-path: "/media"

logging:
    level:
        study.online.media:
            mapper: debug
            service: info
            controller: info

minio:
    endpoint: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin