server:
    port: 8083
    servlet:
        context-path: "/media"

spring:
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB

logging:
    level:
        study.online.media:
            mapper: debug
            service: info
            controller: info

videoprocess:
    ffmpegpath: "D:\\develop\\ffmpeg\\bin\\ffmpeg.exe"