server:
    port: 8082
    servlet:
        context-path: "/media"
spring:
    application:
        name: "media-service"
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: ""
        username: "root"
        password: "000016"