server:
    port: 8083
    servlet:
        context-path: "/media"

spring:
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    rabbitmq:
        host: "127.0.0.1"
        port: 5672
        username: "/study-online"
        password: "000016"

logging:
    level:
        study.online.media:
            mapper: debug
            service: info
            controller: info

videoprocess:
    ffmpegpath: "D:\\develop\\ffmpeg\\bin\\ffmpeg.exe"