server:
    port: 8081

spring:
    application:
        name: content-service
    datasource:
        url: "jdbc:mysql://localhost:3306/so_content?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai"
        driver-class-name: com.mysql.jdbc.Driver
        username: "root"
        password: "000016"

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true